---
  server:
    port: ${PORT:8082}

  spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    mvc:
      hidden-method:
        filter:
          enabled: true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
      hibernate:
        ddl-auto: update
    flyway:
      enabled: false
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${smtp_username}
      password: ${smtp_password}
      properties:
        mail:
          transport:
            protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true
          debug: true
